---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-role
  namespace: web
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments","services"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-binding
  namespace: web
subjects:
- kind: User
  name: gitlab-deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: gitlab-role
  apiGroup: rbac.authorization.k8s.io