# Create an nginx deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: api
        image: 444106639146.dkr.ecr.us-east-1.amazonaws.com/python-fastapi
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m" #cpu is measured in millicores, a milicore is 1/1000 of a core
          limits:
            memory: "128Mi"
            cpu: "500m"

# Create a service type nodeport to expose the nginx deployment
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 8080

